using System;

namespace Hashgraph
{
    /// <summary>
    /// Represents an unexpected termination or exception received
    /// from a mirror stream.
    /// </summary>
    public sealed class MirrorException : Exception
    {
        /// <summary>
        /// Public Constructor.
        /// </summary>
        /// <param name="message">
        /// The message generated by the library describing the 
        /// condition that raised the exception.
        /// </param>
        public MirrorException(string? message, Exception? innerException) : base(message, innerException) { }
    }
}
